# Base docker compose, added to by docker-compose.override or docker-compose.prod. See Readme.md

version: '2'

services:

  # PHP & apache container using offical Docker PHP iamge
  web:
    # If pre-built image from docker hub exists then use that (docker pull openenergymonitor/emoncms:latest) if not Buildcontainer see Dockerflile
    # image: openenergymonitor/emoncms:latest
    build: .
    ports:
      # Expose Emoncms to the world on port 80
      - 80:80
    environment:
      - "MYSQL_HOST=db"
      - "MYSQL_PORT=3306"
      - "MYSQL_DATABASE=emoncms"
      - "MYSQL_USER=emoncms"
      - "MYSQL_PASSWORD=emonpiemoncmsmysql2016"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"

      - "REDIS_ENABLED=true"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_PREFIX='emoncms'"

      - "MQTT_ENABLED=true"
      - "MQTT_HOST=mqtt"
      - "MQTT_USER=emonpi"
      - "MQTT_PASSWORD=emonpimqtt2016"
      - "MQTT_BASETOPIC=emon"

      - "PHPFINA_DIR=/var/opt/emoncms/phpfina/"
      - "PHPTIMESERIES_DIR=/var/opt/emoncms/phptimeseries/"
    volumes:
      # mount docker volumes persistant inside docker container
      - emon-phpfina:/var/opt/emoncms/phpfina
      - emon-phptimeseries:/var/opt/emoncms/phptimeseries
      - emon-cms:/var/www
      - emon-log:/var/log/emoncms
    links:
      # Link to MYSQL DB (see below)
      - db
      - redis
      - mqtt

  demandshaper:
    # If pre-built image from docker hub exists then use that (docker pull openenergymonitor/emoncms:latest) if not Buildcontainer see Dockerflile
    # image: openenergymonitor/emoncms:latest
    build: .
    environment:
      - "MYSQL_HOST=db"
      - "MYSQL_PORT=3306"
      - "MYSQL_DATABASE=emoncms"
      - "MYSQL_USER=emoncms"
      - "MYSQL_PASSWORD=emonpiemoncmsmysql2016"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"

      - "REDIS_ENABLED=true"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_PREFIX='emoncms'"

      - "MQTT_ENABLED=true"
      - "MQTT_HOST=mqtt"
      - "MQTT_USER=emonpi"
      - "MQTT_PASSWORD=emonpimqtt2016"
      - "MQTT_BASETOPIC=emon"

      - "PHPFINA_DIR=/var/opt/emoncms/phpfina/"
      - "PHPTIMESERIES_DIR=/var/opt/emoncms/phptimeseries/"
    volumes:
      # mount docker volumes persistant inside docker container
      - emon-phpfina:/var/opt/emoncms/phpfina
      - emon-phptimeseries:/var/opt/emoncms/phptimeseries
      - emon-cms:/var/www
      - emon-log:/var/log/emoncms
    links:
      # Link to MYSQL DB (see below)
      - db
      - redis
      - mqtt
    command: php /opt/emoncms/demandshaper/demandshaper_run.php

  # MYSQL Database
  db:
    # Official MYSQL docker image
    # To do: make compatiable with 5.7
    image: mariadb:latest
    environment:
      - "MYSQL_HOST=db"
      - "MYSQL_PORT=3306"
      - "MYSQL_DATABASE=emoncms"
      - "MYSQL_USER=emoncms"
      - "MYSQL_PASSWORD=emonpiemoncmsmysql2016"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    volumes:
      - emon-db-data:/var/lib/mysql
    logging:
      driver: json-file
      options:
        max-size: "10m"

  redis:
    # Official redis image
    image: redis:5
    volumes:
      - emon-redis-data:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"

  mqtt:
    image: eclipse-mosquitto:1.6
    ports:
      - 1883:1883

  emoncms_mqtt:
    build: ./emoncms_mqtt
    environment:
      - "MYSQL_HOST=db"
      - "MYSQL_PORT=3306"
      - "MYSQL_DATABASE=emoncms"
      - "MYSQL_USER=emoncms"
      - "MYSQL_PASSWORD=emonpiemoncmsmysql2016"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"

      - "REDIS_ENABLED=true"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_PREFIX='emoncms'"

      - "MQTT_ENABLED=true"
      - "MQTT_HOST=mqtt"
      - "MQTT_USER=emonpi"
      - "MQTT_PASSWORD=emonpimqtt2016"
      - "MQTT_BASETOPIC=emon"

      - "PHPFINA_DIR=/var/opt/emoncms/phpfina/"
      - "PHPTIMESERIES_DIR=/var/opt/emoncms/phptimeseries/"
    links:
      - db
      - redis
    volumes:
      - emon-cms:/var/www
      - emon-log:/var/log/emoncms
    command: php /var/www/emoncms/scripts/services/emoncms_mqtt/emoncms_mqtt.php

volumes:
  emon-phpfiwa:
    driver: local
  emon-phpfina:
    driver: local
  emon-phptimeseries:
    driver: local
  emon-db-data:
    driver: local
  emon-redis-data:
    driver: local
  emon-cms:
    driver: local
  emon-log:
    driver: local
